# Generated by Django 5.1.4 on 2024-12-16 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'managed': False, 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
